//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIL.WordWorks.GAFAWS.AffixPositionAnalyzer.Properties {
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources {

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIL.WordWorks.GAFAWS.AffixPositionAnalyzer.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ample Analysis File.
		/// </summary>
		internal static string kAmpleAnalysisFile {
			get {
				return ResourceManager.GetString("kAmpleAnalysisFile", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Could not load the XSL file..
		/// </summary>
		internal static string kCouldNotLoadFile {
			get {
				return ResourceManager.GetString("kCouldNotLoadFile", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Could not transform the input file..
		/// </summary>
		internal static string kCouldNotTransform {
			get {
				return ResourceManager.GetString("kCouldNotTransform", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ANA files (*.ana)|*.ana|All files (*.*)|*.*.
		/// </summary>
		internal static string kFileTypes {
			get {
				return ResourceManager.GetString("kFileTypes", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Information.
		/// </summary>
		internal static string kInformation {
			get {
				return ResourceManager.GetString("kInformation", resourceCulture);
			}
		}
	}
}
